version: '3.8'
services:
  auth_service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: auth-service
    depends_on:
      - db
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=auth
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - JWT_SECRET=your_jwt_secret_key
    ports:
      - "5000:5000"
    restart: unless-stopped
    volumes:
      - ./:/app

  db:
    image: mysql:latest
    container_name: mysql-auth-db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "4000:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mysql_data: